update

diff --git a/usr/local/bin/arcolinux-desktop-specific-x11 b/usr/local/bin/arcolinux-desktop-specific-x11
--- a/usr/local/bin/arcolinux-desktop-specific-x11
+++ b/usr/local/bin/arcolinux-desktop-specific-x11
@@ -4,25 +4,47 @@ echo "######################################################"
 echo "Begin arcolinux-desktop-specific X11"
 echo "######################################################"
 
-desktop=$(ls /usr/share/xsessions)
+# Detect desktop session
+desktop_file=$(ls /usr/share/xsessions/*.desktop 2>/dev/null | head -n 1)
+desktop=$(basename "$desktop_file")
+
 echo "######################################################"
-echo "This is your current desktop file "$desktop
+echo "Detected desktop session: $desktop"
 echo "######################################################"
-case $desktop in
+
+case "$desktop" in
   leftwm.desktop)
-  echo "Changing arcologout theme"
-  sed -i "s/theme=white/theme=runes/g" /etc/archlinux-logout.conf
-  echo "Changing .bashrc"
-  sed -i "s/neofetch/#neofetch/g" /etc/skel/.bashrc
+    echo "Setting logout theme for LeftWM"
+    sed -i 's/theme=white/theme=runes/g' /etc/archlinux-logout.conf
+
+    echo "Modifying .bashrc to disable neofetch"
+    sed -i 's/^neofetch/#neofetch/g' /etc/skel/.bashrc
     ;;
+  
   chadwm.desktop)
-  echo "Changing arcologout theme"
-  sed -i "s/theme=white/theme=runes/g" /etc/archlinux-logout.conf
-  echo "Changing .bashrc"
-  sed -i "s/neofetch/#neofetch/g" /etc/skel/.bashrc
+    echo "Setting logout theme for ChadWM"
+    sed -i 's/theme=white/theme=runes/g' /etc/archlinux-logout.conf
+
+    # Use getent to find user with UID 1000
+    user=$(getent passwd 1000 | cut -d: -f1)
+
+    echo "###############################################################################"
+    echo "###                 PERSONAL PACMAN HOOK CHADWM START                      ####"
+    echo "###############################################################################"
+    echo
+    echo "Building and installing chadwm for user: $user"
+
+    config_dir="/home/$user/.config/arco-chadwm/chadwm"
+    if [[ -d "$config_dir" ]]; then
+      cd "$config_dir" || exit 1
+      make -B && sudo make install
+    else
+      echo "Directory $config_dir not found. Skipping build."
+    fi
     ;;
+  
   *)
-    echo "Nothing to do"
+    echo "No specific action for desktop: $desktop"
     ;;
 esac
 
